### PR TITLE
Use newer version of mysql-binlog-connector-java

### LINKED ISSUE #49: mysql-binlog-connector-java is no longer maintained
See https://github.com/shyiko/mysql-binlog-connector-java/commit/dd710a5466381faa57442977b24fceff56a0820e we should probably move to the fork at https://github.com/osheroff/mysql-binlog-connector-java

### PR DESCRIPTION
**Pull request by Chrizpy**
Close https://github.com/twingly/ecco/issues/49

The original author is no longer maintaining the one we are using.

### CODE REVIEW

**Comment by walro** [comment]
I was intrigued by the fact that the fork was 6 commits after "upstream", here's the missing stuff:

https://github.com/osheroff/mysql-binlog-connector-java/compare/master...shyiko:master

Wonder if those things have been solved 🤔 

Edit: https://github.com/osheroff/mysql-binlog-connector-java/compare/master...shyiko:c54b4c1 these are the "relevant" changes between the two repos

**Comment by walro** [comment]
> Wonder if those things have been solved 🤔

As far as I can tell, out of the 6 commits, only 3 of them changes anything substantial, these are:

* https://github.com/shyiko/mysql-binlog-connector-java/commit/e59006e7b4566cdf5365bbef6ba212847ec4e253
* https://github.com/shyiko/mysql-binlog-connector-java/commit/c54b4c18ca1c5299792a4be32fa0296a49259362
* https://github.com/shyiko/mysql-binlog-connector-java/commit/5dde1e66159c919933b6b5cbf8c377a12ea88cd8

The last one of these was fixed in the fork too by https://github.com/osheroff/mysql-binlog-connector-java/commit/88de1edf637186ed1d2377d961eb836e95a6c095

However, I don't see the other two being addressed in the fork. They both seem to be a part of solving https://github.com/shyiko/mysql-binlog-connector-java/issues/321 

Not sure if that's an issue for us, but we could see if the fork could pull those changes in for some peace of mind.

Edit: A bit shorter diff version for the stuff that matters: https://github.com/osheroff/mysql-binlog-connector-java/compare/master...shyiko:c54b4c1

**Comment by Chrizpy** [comment]
> I was intrigued by the fact that the fork was 6 commits after "upstream", here's the missing stuff:
> 
> [osheroff/mysql-binlog-connector-java@master...shyiko:master](https://github.com/osheroff/mysql-binlog-connector-java/compare/master...shyiko:master)
> 
> Wonder if those things have been solved 🤔

I was really confused by this comment for a while, I thought you meant that the fork was 6 ahead of the latest commit  on "upstream". But you probably meant that it is 6 commits behind 😄 .

That makes a lot more sense. Seeing as we need (osheroff/mysql-binlog-connector-java@a6a3af7) for the last test case in https://github.com/twingly/ecco/pull/53 to become green, supposedly. Should we switch back to using the old repository then and wait on this fork to progress?

**Comment by walro** [comment]
> But you probably meant that it is 6 commits behind

Yes, I should have typed "behind" instead of "after" :)

**Comment by walro** [comment]
> Should we switch back to using the old repository then and wait on this fork to progress?

Not sure, we need to switch sooner or later. What I was thinking is that we could submit a PR (if it's resonable) with the fix that's missing in the fork.

**Comment by walro** [comment]
BTW, feel free to squash the two commits here :)

**Comment by walro** [comment]
Since we don't use `keepAlive` in our "Ecco clients", I am pretty sure that we won't be affected by https://github.com/shyiko/mysql-binlog-connector-java/issues/321. However, as we allow other users of Ecco to use `keepAlive`, I believe it would be cool if we could get the changes merged into the forked repo.

I will see what can be done, for now I believe we can merge this just to get MySQL 8.0 support going.

**Review by walro — APPROVED** [review]
See comment in https://github.com/twingly/ecco/pull/52#issuecomment-715376899

**Comment by Chrizpy** [comment]
Closing this issue: https://github.com/twingly/ecco/issues/41 since this PR adds MySQL 8.0 support.

**Comment by Chrizpy** [comment]
[Sprint86: Förbered Ecco för MySQL 5.7/8.0](https://trello.com/c/L8dMYtM9/3340-sprint86-f%C3%B6rbered-ecco-f%C3%B6r-mysql-57-80)

**Pull request merged**
