### PR TITLE
Update mysql-binlog-connector dependency to 0.16.1

### LINKED ISSUE #18: Update mysql-binlog-connector
0.3.1 released, we use 0.2.4.

https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md

> Support for "non blocking" mode (equivalent to running mysqlbinlog without --stop-never)

Maybe that could help us somewhere?

### PR DESCRIPTION
**Pull request by walro**
Close #18.

[Changelog](https://github.com/shyiko/mysql-binlog-connector-java/blob/5cfd14276f4a720128ff678dd90e419c327e1704/changelog.md)

Things I think might be good to consider:

* 0.3.0: Support for "non blocking" mode (equivalent to running mysqlbinlog without --stop-never)
* 0.4.1: binlog position tracking (binaryLogClient.binlogPosition is no longer updated on TABLE_MAP so that in case of reconnect (using a different instance of client) table mapping (used by *RowsEventDataDeserializer|s) could be reconstructed before hitting *RowsEvent. (We should see slightly different output in the logging in Ecco clients)
* 0.9.0: BinaryLogClient::connectTimeout (3 seconds by default).
NOTE: BinaryLogClient::keepAliveConnectTimeout has been deprecated and is going to be removed in 1.0.0.
* 0.10.0: BinaryLogClient::heartbeatInterval (118). NOTE: While it's 0 (disabled) by default it's RECOMMENDED that you turn it on (regardless whether you use built-in keepAlive mechanism or not).

Since the library adheres to semver I think we can bump to 0.8.0 if we merge this. (We're currently on 0.7.0).

### CODE REVIEW

**Comment by walro** [comment]
WIP until we have addressed the new setters/getters needed for `connectTimeout` and `heartbeatInterval`.

**Comment by walro** [comment]
Since this PR was opened, a few more versions have arrived (0.14, 0.15, 0.16, 0.16.1):

https://github.com/shyiko/mysql-binlog-connector-java/blob/master/CHANGELOG.md

**Comment by walro** [comment]
> Since this PR was opened, a few more versions have arrived (0.14, 0.15, 0.16, 0.16.1):

2b08b87308200d09855c243b60060751dac68d04

**Comment by walro** [comment]
I think we are ready  🙏

**Comment by roback** [comment]
> I think we are ready 🙏

Yes, I think so too :)

**Review by roback — APPROVED** [review]
Feels wrong to review this myself, but LGTM :)

**Pull request merged**
